import type { Metadata } from "next";
import "./globals.css";
import ModalProvider from "@/providers/ModalProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "pa-Appointment",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ModalProvider />
                <Toaster />
                {children}
            </body>
        </html>
    );
}
